actions: test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -3,44 +3,115 @@ name: Test
 on:
   push:
     branches:
-      - master
+      - main
       - develop
   pull_request:
 
-env:
-  CI_TOKEN: ${{ secrets.CI_TOKEN }}
-  CI_USER: ${{ secrets.CI_USER }}
-
 permissions:
-  actions: read
   contents: write
   pull-requests: write
 
 jobs:
   test:
-    timeout-minutes: 10
-    name: Test
-    runs-on: ubuntu-latest
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [ubuntu-latest, macos-latest, windows-latest]
+
     steps:
       - name: checkout
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-
-      - name: Set up Go
-        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
+        uses: actions/checkout@v6
+      - name: setup go
+        uses: actions/setup-go@v6
         with:
           go-version-file: go.mod
 
       - name: test
-        run: |
-          go run gotest.tools/gotestsum@latest \
-            --junitfile unit-tests.xml \
-            --format pkgname -- -coverprofile=coverage.out $(go list ./... | grep -Ev '(cmd|testutil|mocks)')
+        env:
+          GITHUB_TOKEN: ${{ matrix.os == 'ubuntu-latest' && secrets.GITHUB_TOKEN || '' }} # Needed for GitHub badge storer integration test
+        run: go test -race -count=1 -failfast -shuffle=on -coverprofile=${{ matrix.os }}-profile -covermode=atomic -coverpkg=./... ./...
 
-      - name: octocov report
-        uses: k1LoW/octocov-action@1ad702b3118b6a055c00b01db68ca0d9f6641dbc # v1.4.0
-
-      - name: Test Summary
-        uses: test-summary/action@v2
+      - name: upload cover profile artifact
+        uses: actions/upload-artifact@v5
         with:
-          paths: unit-tests.xml
-        if: always()
+          name: ${{ matrix.os }}-profile
+          path: ${{ matrix.os }}-profile
+          if-no-files-found: error
+
+  check-coverage:
+    runs-on: ubuntu-latest
+    needs: test
+
+    steps:
+      - name: checkout
+        uses: actions/checkout@v6
+
+      - name: download ubuntu-latest-profile
+        uses: actions/download-artifact@v6
+        with:
+          name: ubuntu-latest-profile
+      - name: download macos-latest-profile
+        uses: actions/download-artifact@v6
+        with:
+          name: macos-latest-profile
+      - name: download windows-latest-profile
+        uses: actions/download-artifact@v6
+        with:
+          name: windows-latest-profile
+
+      - name: download artifact (main.breakdown)
+        id: download-main-breakdown
+        uses: dawidd6/action-download-artifact@v14
+        with:
+          branch: main
+          workflow_conclusion: success
+          name: main.breakdown
+          if_no_artifact_found: fail
+
+      - name: check test coverage
+        id: coverage
+        uses: vladopajic/go-test-coverage@v2
+        continue-on-error: true # Should fail after coverage comment is posted
+        with:
+          config: ./.github/.testcoverage.yml
+          profile: ubuntu-latest-profile,macos-latest-profile,windows-latest-profile
+          git-branch: badges
+          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
+          breakdown-file-name: ${{ github.ref_name == 'main' && 'main.breakdown' || '' }}
+          diff-base-breakdown-file-name: ${{ steps.download-main-breakdown.outputs.found_artifact == 'true' && 'main.breakdown' || '' }}
+
+      - name: upload artifact (main.breakdown)
+        uses: actions/upload-artifact@v5
+        if: github.ref_name == 'main'
+        with:
+          name: main.breakdown
+          path: main.breakdown
+          if-no-files-found: error
+
+      - name: find pull request ID
+        run: |
+          PR_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ github.ref_name }}&state=open")
+          PR_ID=$(echo "$PR_DATA" | jq -r '.[0].number')
+          
+          if [ "$PR_ID" != "null" ]; then
+            echo "pull_request_id=$PR_ID" >> $GITHUB_ENV
+          else
+            echo "No open pull request found for this branch."
+          fi
+      - name: post coverage report
+        if: env.pull_request_id
+        uses: thollander/actions-comment-pull-request@v3
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          comment-tag: coverage-report
+          pr-number: ${{ env.pull_request_id }}
+          message: |
+            go-test-coverage report:
+            ``` 
+            ${{ fromJSON(steps.coverage.outputs.report) }}```
+
+      - name: "finally check coverage"
+        if: steps.coverage.outcome == 'failure'
+        shell: bash
+        run: echo "coverage check failed" && exit 1
